### PR TITLE
fix indentation of PDB template's labels

### PR DESCRIPTION
**Pull request by nweisenauer-sap**
**What this PR does / why we need it**:
fixes syntax error in the PDB template, labels should be on the level of metadata
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
fixes syntax error in the PDB template
```

### CODE REVIEW

**Comment by ghost** [comment]
@nweisenauer-sap Thank you for your contribution.

**Comment by gardener-robot-ci-2** [comment]
Thank you @nweisenauer-sap for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by dimityrmirchev — CHANGES_REQUESTED** [review]
Thanks for this fix. Can you please use two spaces instead of a single '\t' so it is consistent with other templates as well?

See the [hpa template as an example](https://github.com/gardener/service-account-issuer-discovery/blob/19ab69bd7c9fe684898367a6b31071887e09e76a/charts/service-account-issuer-discovery/templates/hpa.yaml)

**Comment by nweisenauer-sap** [comment]
sure, thx, please double check

**Review by dimityrmirchev — APPROVED** [review]
Thanks!

/lgtm

**Pull request merged**
